apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: varunraju2004/cicd-app:<TAG>
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-app-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: cicd-app
